### ISSUE TITLE
Profile : Fix `github-readme-stats`-related error

### ISSUE THREAD

**Issue by kimpro82** [kimpro82/kimpro82#10]
![2022-05-17 profile error](https://user-images.githubusercontent.com/23569014/168839824-9b87317a-71f9-4f36-9788-c925f140b1b9.PNG)

- reference :
  https://github.com/anuraghazra/github-readme-stats/issues/852

**Comment by ashishtele** [comment]
Is the server down? Getting same error

**Comment by khitermedachraf** [comment]
Same error for me too

**Comment by ZacDair** [comment]
same error - using https://github-readme-stats.vercel.app

**Comment by khitermedachraf** [comment]
### For me, I just changed this link: `https://github-readme-stats.vercel.app/`
### To  `https://github-readme-stats-eight-theta.vercel.app`
### and it works fine now ✔🎉

**Comment by khitermedachraf** [comment]
### even for the second stats that have the same old link.

**Comment by Kymoraa** [comment]
> ### For me, I just changed this link: `https://github-readme-stats.vercel.app/`
> ### To `https://github-readme-stats-eight-theta.vercel.app`
> ### and it works fine now ✔🎉

I have tried this too and it's now working.
Thanks for the tip

**Comment by kimpro82** [comment]
To my surprise, although I didn't do any treatements yet, but the problem seems to be solved by the responsible organizer. My profile has been recovered now like the below :

![2022-05-18 profile error](https://user-images.githubusercontent.com/23569014/169073011-815cf7af-d291-4009-97e4-e1d141395b97.PNG)

**Comment by kimpro82** [comment]
Died again

https://github.com/anuraghazra/github-readme-stats/issues/3851

**Comment by kimpro82** [comment]
I've decided to move to https://github.com/pranesh-2005/github-readme-stats-fast
